version: '3.4'

services:
  eshopdb:
    image: postgres
    
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Bootstrapper/Api/Dockerfile

  distributedcache:
    image: redis

  messagebus:
    image: rabbitmq:3.13-management

volumes:
  postgres_eshopdb: